http:
  routers:
    homeassistant:
      rule: "Host(`hass.internal`)"
      entrypoints:
        - web
      service: homeassistant

    zigbee2mqtt:
      rule: "Host(`z2m.internal`)"
      entrypoints:
        - web
      service: zigbee2mqtt

  services:
    homeassistant:
      loadBalancer:
        servers:
          - url: "http://127.0.0.1:8123"

    zigbee2mqtt:
      loadBalancer:
        servers:
          - url: "http://127.0.0.1:8099"
